version: "3.8"

volumes:
  php-fpm-socket:
    driver_opts:
      type: none
      device: $PWD/var/run/php-fpm
      o: bind

services:
  app:               # set this line
    build: ./docker/app
    volumes:
      - php-fpm-socket:/var/run/php-fpm
      - ./www:/var/www
    user: appagent
    working_dir: /var/www

  web:               # set this line
    build: ./docker/web
    volumes:
      - ./www:/var/www
      - php-fpm-socket:/var/run/php-fpm
    ports:
      - 80:80        # if needed, change this line and "web/nginx/conf.d/app.conf.template"
      - 443:443      # if needed, change this line and "web/nginx/conf.d/app.conf.template"
    environment:
      SERVER_NAME: 192.168.99.100
      PHP_SOCKET: /var/run/php-fpm/php-fpm.sock
    command: sh -c "envsubst '$$SERVER_NAME $$PHP_SOCKET' < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - app

  mysql:                # set this line and use this name in docker environment
    ports:
      - 13306:3306
    build: ./docker/db
    volumes:
      - ./misc/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=mysql
    links:
      - mysql
    ports:
        - 8080:80
    volumes:
        - ./phpmyadmin/sessions:/sessions